### ISSUE TITLE
How to download OpenImages v3 (2017.11) training set fastly and completely?

### ISSUE THREAD

**Issue by ChazzyGordon** [hbdat/cvpr20_IMCL#2]
Downloading the  OpenImages v3 (2017.11) training set costs too much time and many images are unavailable, so how to download OpenImages v3 (2017.11) training set fastly and completely? Could you please provide a download link for your experimenting dataset since it seems that the codes doesn't take the full OpenImages dataset for training? Thank you!

Reported bugs always occur when downloading with the script (`python download_imgs/asyn_image_downloader.py`):
```
<class 'OSError'>
<class 'OSError'>
drop image
<class 'OSError'>
Traceback (most recent call last):
  File "download_imgs/asyn_image_downloader.py", line 160, in <module>
    res=parallel_process(image_infos, download,n_jobs)
  File "download_imgs/asyn_image_downloader.py", line 53, in parallel_process
    futures = [pool.submit(function, a) for a in array[front_num:]]
  File "download_imgs/asyn_image_downloader.py", line 53, in <listcomp>
    futures = [pool.submit(function, a) for a in array[front_num:]]
  File "/usr/lib64/python3.6/concurrent/futures/process.py", line 452, in submit
    raise BrokenProcessPool('A child process terminated '
concurrent.futures.process.BrokenProcessPool: A child process terminated abruptly, the process pool is not usable anymore
```

**Comment by hbdat** [comment]
Hi Taian Guo,

Thanks for reaching out.

Google has gathered all the images in Open Images and hosted them online. 
You can now directly download all images.
Please refer to https://storage.googleapis.com/openimages/web/download.html for two hosts that you can download from.

Back when I was working on the project, these hosts were not available so I had to collect all images manually.

Best,
Dat

**Comment by ChazzyGordon** [comment]
Hi Dat,

I think I'll try the google free download API for OpenImages. 

Thank you so much for you kind reply!

Best,
Taian
