### ISSUE TITLE
missing files for training

### ISSUE THREAD

**Issue by ChazzyGordon** [hbdat/cvpr20_IMCL#3]
These following necessary files are unavailable:
```
label_graph/graph_label_naive.npy
result/baseline_logistic_OpenImages.npz
```

Please provide these required files so as to start training. Thank you!

Reported bugs when running `python OpenImages_experiments/baseline_logistic_OpenImages.py`:
```
Traceback (most recent call last):
  File "OpenImages_experiments/baseline_logistic_OpenImages.py", line 173, in <module>
    G = np.load('./label_graph/graph_label_naive.npy').astype(np.float32)
  File "/usr/local/lib64/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './label_graph/graph_label_naive.npy'
```

Reported bugs when running `python OpenImages_experiments/interactive_learning_OpenImages.py`:
```
Traceback (most recent call last):
  File "OpenImages_experiments/interactive_learning_OpenImages.py", line 151, in <module>
    data = np.load(global_setting_OpenImage.saturated_Thetas_model)
  File "/usr/local/lib64/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './result/baseline_logistic_OpenImages.npz'
```

**Comment by hbdat** [comment]
Thanks for spotting these missing files.

Since these files are too big for Github (probably why they are missing on github), I upload them on google drive under the following links:

`result/baseline_logistic_OpenImages.npz`
https://drive.google.com/file/d/1our5lctu-H567VjX20X9TSgiGINIAPzz/view?usp=sharing

`label_graph/graph_label_naive.npy`
https://drive.google.com/file/d/1kg0UeInk33cKadq8rEU3i-3wSm3Oq7Oh/view?usp=sharing

I have also updated the ReadMe file to include these links.

Best,
Dat

**Comment by ChazzyGordon** [comment]
Hi Dat,
Thank you for your kind reply! I can run `python OpenImages_experiments/baseline_logistic_OpenImages.py` and `python OpenImages_experiments/interactive_learning_OpenImages.py` with the provided two files. However, I encounter similar problems when run other python scripts for end-to-end training (`python ./OpenImages_experiments/e2e_interactive_learning_OpenImages.py`). Missing files list:
```
result/interactive_learning_OpenImages/models_ES.npz
label_graph/graph_label_mixture.npz
and other `.npy` or `.npz` files in the codes.
```
[Git LFS](https://git-lfs.github.com/) can be helpful for pushing large files to git remote repository conveniently, by the way. Maybe you can give it a try.

Thank you so much for your patience!

Best,
Taian

**Comment by hbdat** [comment]
Hi Taian,

Thanks for your feedback and suggestion of Git LFS. 

1) The `result/interactive_learning_OpenImages/models_ES.npz` should be the output of `python OpenImages_experiments/interactive_learning_OpenImages.py`. 
Thus, you need to run `interactive_learning_OpenImages.py` before `e2e_interactive_learning_OpenImages.py` as `e2e_interactive_learning_OpenImages.py` uses the model from `interactive_learning_OpenImages.py` as initialization.
For ease of running, I have uploaded the `models_ES.npz` under the following link:
https://drive.google.com/file/d/1WVg89E6sOxXnAcAXgltzFmZUT-OlvzqX/view?usp=sharing

2) There should not be a `label_graph/graph_label_mixture.npz` graph.
The label graph path should be `label_graph/graph_label_naive.npy` for both end-to-end and fixed-feature training.
Could you please provide the lines of error so I can correct this (somehow I could not find this error in the code)? 

Let me know if there are other missing files.

Best,
Dat
